package com.signalwire.agents;

import com.signalwire.agents.agent.AgentBase;
import com.signalwire.agents.security.SessionManager;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for authentication: basic auth, auto-generation, timing-safe comparison,
 * environment variable override, and session token management.
 */
class AuthTest {

    // ======== Auto-generated credentials ========

    @Test
    void testAutoGeneratedPassword() {
        AgentBase agent = AgentBase.builder()
                .name("auto-auth")
                .authUser("testuser")
                .build();
        assertNotNull(agent.getAuthPassword());
        assertFalse(agent.getAuthPassword().isEmpty());
    }

    @Test
    void testAutoGeneratedUserFromName() {
        // When no env var and no explicit user, authUser falls back to agent name
        String envUser = System.getenv("SWML_BASIC_AUTH_USER");
        if (envUser == null || envUser.isEmpty()) {
            AgentBase agent = AgentBase.builder()
                    .name("my-agent")
                    .build();
            assertEquals("my-agent", agent.getAuthUser());
        }
    }

    @Test
    void testExplicitAuth() {
        AgentBase agent = AgentBase.builder()
                .name("test")
                .authUser("alice")
                .authPassword("s3cret")
                .build();
        assertEquals("alice", agent.getAuthUser());
        assertEquals("s3cret", agent.getAuthPassword());
    }

    @Test
    void testAutoGeneratedPasswordIsDifferentEachTime() {
        // This test only works when SWML_BASIC_AUTH_PASSWORD env var is NOT set
        String envPass = System.getenv("SWML_BASIC_AUTH_PASSWORD");
        if (envPass != null && !envPass.isEmpty()) {
            // Env var is set, both agents will get the same password from env
            AgentBase a1 = AgentBase.builder().name("a").authUser("u").build();
            assertEquals(envPass, a1.getAuthPassword());
        } else {
            AgentBase a1 = AgentBase.builder().name("a").authUser("u").build();
            AgentBase a2 = AgentBase.builder().name("a").authUser("u").build();
            // Auto-generated passwords should be different across instances
            assertNotEquals(a1.getAuthPassword(), a2.getAuthPassword());
        }
    }

    // ======== SessionManager timing-safe token ========

    @Test
    void testTimingSafeTokenCreation() {
        SessionManager sm = new SessionManager();
        String token = sm.createToken("func", "call");
        assertNotNull(token);
        assertTrue(token.contains("."));
        assertTrue(sm.validateToken(token, "func", "call"));
    }

    @Test
    void testTimingSafeTokenRejectsWrongFunction() {
        SessionManager sm = new SessionManager();
        String token = sm.createToken("func", "call");
        assertFalse(sm.validateToken(token, "wrong", "call"));
    }

    @Test
    void testTimingSafeTokenRejectsWrongCall() {
        SessionManager sm = new SessionManager();
        String token = sm.createToken("func", "call");
        assertFalse(sm.validateToken(token, "func", "wrong"));
    }

    @Test
    void testTimingSafeTokenRejectsTampered() {
        SessionManager sm = new SessionManager();
        String token = sm.createToken("func", "call");
        String tampered = "tampered" + token.substring(8);
        assertFalse(sm.validateToken(tampered, "func", "call"));
    }

    @Test
    void testTimingSafeTokenRejectsNull() {
        SessionManager sm = new SessionManager();
        assertFalse(sm.validateToken(null, "func", "call"));
    }

    @Test
    void testTimingSafeTokenRejectsEmpty() {
        SessionManager sm = new SessionManager();
        assertFalse(sm.validateToken("", "func", "call"));
    }

    @Test
    void testTimingSafeTokenRejectsExpired() {
        SessionManager sm = new SessionManager();
        String token = sm.createToken("func", "call", -10);
        assertFalse(sm.validateToken(token, "func", "call"));
    }

    @Test
    void testTimingSafeTokenCustomExpiry() {
        SessionManager sm = new SessionManager();
        String token = sm.createToken("func", "call", 7200);
        assertTrue(sm.validateToken(token, "func", "call"));
    }

    @Test
    void testDifferentManagersDifferentSecrets() {
        SessionManager sm1 = new SessionManager();
        SessionManager sm2 = new SessionManager();
        String token = sm1.createToken("func", "call");
        assertFalse(sm2.validateToken(token, "func", "call"));
    }

    // ======== Secure tool integration ========

    @Test
    void testSecureToolRejectsWithoutToken() {
        AgentBase agent = AgentBase.builder()
                .name("test")
                .authUser("u")
                .authPassword("p")
                .build();
        var td = new com.signalwire.agents.swaig.ToolDefinition(
                "secure_func", "Secure function", java.util.Map.of(),
                (a, r) -> new com.signalwire.agents.swaig.FunctionResult("secret"));
        td.setSecure(true);
        agent.defineTool(td);

        var result = agent.onFunctionCall("secure_func", java.util.Map.of(), java.util.Map.of());
        assertTrue(result.getResponse().contains("Unauthorized"));
    }

    // ======== Environment variable auth ========

    @Test
    void testEnvVarAuthUser() {
        String envUser = System.getenv("SWML_BASIC_AUTH_USER");
        if (envUser != null && !envUser.isEmpty()) {
            AgentBase agent = AgentBase.builder().name("test").build();
            assertEquals(envUser, agent.getAuthUser());
        }
    }

    @Test
    void testEnvVarAuthPassword() {
        String envPass = System.getenv("SWML_BASIC_AUTH_PASSWORD");
        if (envPass != null && !envPass.isEmpty()) {
            AgentBase agent = AgentBase.builder().name("test").authUser("u").build();
            assertEquals(envPass, agent.getAuthPassword());
        }
    }
}
