package com.signalwire.sdk;

import static org.junit.jupiter.api.Assertions.*;

import com.signalwire.sdk.agent.AgentBase;
import com.signalwire.sdk.security.SessionManager;
import org.junit.jupiter.api.Test;

/**
 * Tests for authentication: basic auth, auto-generation, timing-safe comparison, environment
 * variable override, and session token management.
 */
class AuthTest {

  // ======== Auto-generated credentials ========

  @Test
  void testAutoGeneratedPassword() {
    AgentBase agent = AgentBase.builder().name("auto-auth").authUser("testuser").build();
    assertNotNull(agent.getAuthPassword());
    assertFalse(agent.getAuthPassword().isEmpty());
  }

  @Test
  void testAutoGeneratedUserFromName() {
    // When no env var and no explicit user, authUser falls back to agent name
    String envUser = System.getenv("SWML_BASIC_AUTH_USER");
    if (envUser == null || envUser.isEmpty()) {
      AgentBase agent = AgentBase.builder().name("my-agent").build();
      assertEquals("my-agent", agent.getAuthUser());
    }
  }

  @Test
  void testExplicitAuth() {
    AgentBase agent =
        AgentBase.builder().name("test").authUser("alice").authPassword("s3cret").build();
    assertEquals("alice", agent.getAuthUser());
    assertEquals("s3cret", agent.getAuthPassword());
  }

  @Test
  void testAutoGeneratedPasswordIsDifferentEachTime() {
    // This test only works when SWML_BASIC_AUTH_PASSWORD env var is NOT set
    String envPass = System.getenv("SWML_BASIC_AUTH_PASSWORD");
    if (envPass != null && !envPass.isEmpty()) {
      // Env var is set, both agents will get the same password from env
      AgentBase a1 = AgentBase.builder().name("a").authUser("u").build();
      assertEquals(envPass, a1.getAuthPassword());
    } else {
      AgentBase a1 = AgentBase.builder().name("a").authUser("u").build();
      AgentBase a2 = AgentBase.builder().name("a").authUser("u").build();
      // Auto-generated passwords should be different across instances
      assertNotEquals(a1.getAuthPassword(), a2.getAuthPassword());
    }
  }

  // ======== SessionManager timing-safe token ========

  @Test
  void testTimingSafeTokenCreation() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call");
    assertNotNull(token);
    assertFalse(token.isEmpty());
    assertTrue(sm.validateToken(token, "func", "call"));
  }

  @Test
  void testTimingSafeTokenRejectsWrongFunction() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call");
    assertFalse(sm.validateToken(token, "wrong", "call"));
  }

  @Test
  void testTimingSafeTokenRejectsWrongCall() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call");
    assertFalse(sm.validateToken(token, "func", "wrong"));
  }

  @Test
  void testTimingSafeTokenRejectsTampered() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call");
    String tampered = "tampered" + token.substring(8);
    assertFalse(sm.validateToken(tampered, "func", "call"));
  }

  @Test
  void testTimingSafeTokenRejectsNull() {
    SessionManager sm = new SessionManager();
    assertFalse(sm.validateToken(null, "func", "call"));
  }

  @Test
  void testTimingSafeTokenRejectsEmpty() {
    SessionManager sm = new SessionManager();
    assertFalse(sm.validateToken("", "func", "call"));
  }

  @Test
  void testTimingSafeTokenRejectsExpired() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call", -10);
    assertFalse(sm.validateToken(token, "func", "call"));
  }

  @Test
  void testTimingSafeTokenCustomExpiry() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call", 7200);
    assertTrue(sm.validateToken(token, "func", "call"));
  }

  @Test
  void testDifferentManagersDifferentSecrets() {
    SessionManager sm1 = new SessionManager();
    SessionManager sm2 = new SessionManager();
    String token = sm1.createToken("func", "call");
    assertFalse(sm2.validateToken(token, "func", "call"));
  }

  // ======== Secure tool integration ========

  @Test
  @SuppressWarnings("unchecked")
  void testSecureToolRendersWebhookToken() {
    // A1 secure contract (SECURE-DEFAULT gate): the per-tool SWAIG token is a WIRE artifact — a
    // secure tool's RENDERED webhook carries a meta_data_token; an insecure one does not. (Matching
    // the Python reference, onFunctionCall dispatches WITHOUT validating the token; the /swaig HTTP
    // handler validates the round-tripped token, so it is the rendered surface that is pinned
    // here.)
    AgentBase agent = AgentBase.builder().name("test").authUser("u").authPassword("p").build();
    agent.setPromptText("Test");
    agent.defineTool(
        new com.signalwire.sdk.swaig.ToolDefinition(
            "secure_func",
            "Secure function",
            java.util.Map.of(),
            (a, r) -> new com.signalwire.sdk.swaig.FunctionResult("secret")));
    agent.defineTool(
        new com.signalwire.sdk.swaig.ToolDefinition(
                "insecure_func",
                "Insecure function",
                java.util.Map.of(),
                (a, r) -> new com.signalwire.sdk.swaig.FunctionResult("open"))
            .setSecure(false));

    var swml = agent.renderSwml("http://localhost:3000");
    var sections = (java.util.Map<String, Object>) swml.get("sections");
    var main = (java.util.List<java.util.Map<String, Object>>) sections.get("main");
    var ai =
        main.stream()
            .filter(v -> v.containsKey("ai"))
            .findFirst()
            .map(v -> (java.util.Map<String, Object>) v.get("ai"))
            .orElseThrow();
    var swaig = (java.util.Map<String, Object>) ai.get("SWAIG");
    var functions = (java.util.List<java.util.Map<String, Object>>) swaig.get("functions");

    var secure =
        functions.stream()
            .filter(fn -> "secure_func".equals(fn.get("function")))
            .findFirst()
            .orElseThrow();
    var insecure =
        functions.stream()
            .filter(fn -> "insecure_func".equals(fn.get("function")))
            .findFirst()
            .orElseThrow();

    // secure tool (the A1 default) → rendered webhook carries a token; insecure tool → none.
    assertNotNull(secure.get("meta_data_token"), "secure tool must render a webhook token");
    assertFalse(String.valueOf(secure.get("meta_data_token")).isEmpty(), "token must be non-empty");
    assertNull(insecure.get("meta_data_token"), "insecure tool must NOT render a webhook token");
  }

  // ======== Environment variable auth ========

  @Test
  void testEnvVarAuthUser() {
    String envUser = System.getenv("SWML_BASIC_AUTH_USER");
    if (envUser != null && !envUser.isEmpty()) {
      AgentBase agent = AgentBase.builder().name("test").build();
      assertEquals(envUser, agent.getAuthUser());
    }
  }

  @Test
  void testEnvVarAuthPassword() {
    String envPass = System.getenv("SWML_BASIC_AUTH_PASSWORD");
    if (envPass != null && !envPass.isEmpty()) {
      AgentBase agent = AgentBase.builder().name("test").authUser("u").build();
      assertEquals(envPass, agent.getAuthPassword());
    }
  }
}
