package com.signalwire.sdk;

import static org.junit.jupiter.api.Assertions.*;

import com.signalwire.sdk.agent.AgentBase;
import com.signalwire.sdk.security.SessionManager;
import org.junit.jupiter.api.Test;

/**
 * Tests for authentication: basic auth, auto-generation, timing-safe comparison, environment
 * variable override, and session token management.
 */
class AuthTest {

  // ======== Auto-generated credentials ========

  @Test
  void testAutoGeneratedPassword() {
    AgentBase agent = AgentBase.builder().name("auto-auth").authUser("testuser").build();
    assertNotNull(agent.getAuthPassword());
    assertFalse(agent.getAuthPassword().isEmpty());
  }

  @Test
  void testAutoGeneratedUserFromName() {
    // When no env var and no explicit user, authUser falls back to agent name
    String envUser = System.getenv("SWML_BASIC_AUTH_USER");
    if (envUser == null || envUser.isEmpty()) {
      AgentBase agent = AgentBase.builder().name("my-agent").build();
      assertEquals("my-agent", agent.getAuthUser());
    }
  }

  @Test
  void testExplicitAuth() {
    AgentBase agent =
        AgentBase.builder().name("test").authUser("alice").authPassword("s3cret").build();
    assertEquals("alice", agent.getAuthUser());
    assertEquals("s3cret", agent.getAuthPassword());
  }

  @Test
  void testAutoGeneratedPasswordIsDifferentEachTime() {
    // This test only works when SWML_BASIC_AUTH_PASSWORD env var is NOT set
    String envPass = System.getenv("SWML_BASIC_AUTH_PASSWORD");
    if (envPass != null && !envPass.isEmpty()) {
      // Env var is set, both agents will get the same password from env
      AgentBase a1 = AgentBase.builder().name("a").authUser("u").build();
      assertEquals(envPass, a1.getAuthPassword());
    } else {
      AgentBase a1 = AgentBase.builder().name("a").authUser("u").build();
      AgentBase a2 = AgentBase.builder().name("a").authUser("u").build();
      // Auto-generated passwords should be different across instances
      assertNotEquals(a1.getAuthPassword(), a2.getAuthPassword());
    }
  }

  // ======== SessionManager timing-safe token ========

  @Test
  void testTimingSafeTokenCreation() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call");
    assertNotNull(token);
    assertFalse(token.isEmpty());
    assertTrue(sm.validateToken(token, "func", "call"));
  }

  @Test
  void testTimingSafeTokenRejectsWrongFunction() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call");
    assertFalse(sm.validateToken(token, "wrong", "call"));
  }

  @Test
  void testTimingSafeTokenRejectsWrongCall() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call");
    assertFalse(sm.validateToken(token, "func", "wrong"));
  }

  @Test
  void testTimingSafeTokenRejectsTampered() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call");
    String tampered = "tampered" + token.substring(8);
    assertFalse(sm.validateToken(tampered, "func", "call"));
  }

  @Test
  void testTimingSafeTokenRejectsNull() {
    SessionManager sm = new SessionManager();
    assertFalse(sm.validateToken(null, "func", "call"));
  }

  @Test
  void testTimingSafeTokenRejectsEmpty() {
    SessionManager sm = new SessionManager();
    assertFalse(sm.validateToken("", "func", "call"));
  }

  @Test
  void testTimingSafeTokenRejectsExpired() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call", -10);
    assertFalse(sm.validateToken(token, "func", "call"));
  }

  @Test
  void testTimingSafeTokenCustomExpiry() {
    SessionManager sm = new SessionManager();
    String token = sm.createToken("func", "call", 7200);
    assertTrue(sm.validateToken(token, "func", "call"));
  }

  @Test
  void testDifferentManagersDifferentSecrets() {
    SessionManager sm1 = new SessionManager();
    SessionManager sm2 = new SessionManager();
    String token = sm1.createToken("func", "call");
    assertFalse(sm2.validateToken(token, "func", "call"));
  }

  // ======== Secure tool integration ========

  @Test
  @SuppressWarnings("unchecked")
  void testSecureToolRendersWebhookToken() {
    // A1 secure contract (SECURE-DEFAULT gate): the per-tool SWAIG token is a WIRE artifact — a
    // secure tool's RENDERED webhook carries a `__token` QUERY PARAMETER on its own web_hook_url,
    // and an insecure tool gets NO per-tool web_hook_url at all (it falls back to
    // SWAIG.defaults.web_hook_url). Matching the Python reference (agent_base.py:1096-1100).
    //
    // This test previously asserted `meta_data_token`, which is a DIFFERENT SWML field: schema.json
    // defines it as the "Scoping token for meta_data", the engine MD5-derives it from
    // web_hook_url+auth when the SWML omits it (mod_openai/app_config.c:1031-1042) and uses it only
    // as a key into the per-function metadata store (actions.c:2085-2093). Nothing validates it as
    // a credential, so a token placed there left the callback unauthenticated.
    //
    // (Matching the Python reference, onFunctionCall dispatches WITHOUT validating the token; the
    // /swaig HTTP handler validates the round-tripped token, so it is the rendered surface that is
    // pinned here.)
    AgentBase agent = AgentBase.builder().name("test").authUser("u").authPassword("p").build();
    agent.setPromptText("Test");
    agent.defineTool(
        new com.signalwire.sdk.swaig.ToolDefinition(
            "secure_func",
            "Secure function",
            java.util.Map.of(),
            (a, r) -> new com.signalwire.sdk.swaig.FunctionResult("secret")));
    agent.defineTool(
        new com.signalwire.sdk.swaig.ToolDefinition(
                "insecure_func",
                "Insecure function",
                java.util.Map.of(),
                (a, r) -> new com.signalwire.sdk.swaig.FunctionResult("open"))
            .setSecure(false));

    var swml = agent.renderSwml("http://localhost:3000");
    var sections = (java.util.Map<String, Object>) swml.get("sections");
    var main = (java.util.List<java.util.Map<String, Object>>) sections.get("main");
    var ai =
        main.stream()
            .filter(v -> v.containsKey("ai"))
            .findFirst()
            .map(v -> (java.util.Map<String, Object>) v.get("ai"))
            .orElseThrow();
    var swaig = (java.util.Map<String, Object>) ai.get("SWAIG");
    var functions = (java.util.List<java.util.Map<String, Object>>) swaig.get("functions");

    var secure =
        functions.stream()
            .filter(fn -> "secure_func".equals(fn.get("function")))
            .findFirst()
            .orElseThrow();
    var insecure =
        functions.stream()
            .filter(fn -> "insecure_func".equals(fn.get("function")))
            .findFirst()
            .orElseThrow();

    // secure tool (the A1 default) → its OWN web_hook_url carries ?__token=<hmac>.
    String secureUrl = (String) secure.get("web_hook_url");
    assertNotNull(secureUrl, "secure tool must render its own web_hook_url");
    assertTrue(
        secureUrl.contains("__token="),
        "secure tool's webhook must carry the __token query param: " + secureUrl);
    assertFalse(
        secureUrl.endsWith("__token="), "the __token query param must have a value: " + secureUrl);

    // The token must NOT be written to meta_data_token — that is the SWML metadata SCOPING key,
    // not a credential (see the comment above).
    assertNull(
        secure.get("meta_data_token"),
        "the security token must not be emitted as meta_data_token (a metadata scoping key)");

    // insecure tool → NO per-tool webhook at all, so no token anywhere.
    assertNull(
        insecure.get("web_hook_url"),
        "insecure tool must render NO per-tool web_hook_url (it falls back to SWAIG.defaults)");
    assertNull(insecure.get("meta_data_token"), "insecure tool must NOT render a webhook token");
  }

  @Test
  @SuppressWarnings("unchecked")
  void testSwaigDefaultsWebHookUrlIsEmittedWhenFunctionsExist() {
    // The other half of the secure contract. Because an INSECURE tool deliberately renders no
    // per-tool web_hook_url, `SWAIG.defaults.web_hook_url` is the ONLY endpoint it has — so a
    // missing defaults block does not merely differ from the reference, it leaves the tool with
    // no callback at all. The reference emits it alongside functions (agent_base.py:1108-1113).
    AgentBase agent =
        AgentBase.builder().name("test").route("/a").authUser("u").authPassword("p").build();
    agent.setPromptText("Test");
    agent.defineTool(
        new com.signalwire.sdk.swaig.ToolDefinition(
                "insecure_tool",
                "insecure",
                java.util.Map.of(),
                (a, r) -> new com.signalwire.sdk.swaig.FunctionResult("ok"))
            .setSecure(false));

    var swml = agent.renderSwml("http://localhost:3000");
    var swaig = swaigOf(swml);

    var defaults = (java.util.Map<String, Object>) swaig.get("defaults");
    assertNotNull(defaults, "SWAIG.defaults must be emitted when functions exist");
    assertEquals(
        "http://localhost:3000/a/swaig",
        defaults.get("web_hook_url"),
        "defaults.web_hook_url is the shared fallback endpoint, WITHOUT a per-tool token");

    // And the insecure tool really does rely on it: it has no webhook of its own.
    var fns = (java.util.List<java.util.Map<String, Object>>) swaig.get("functions");
    assertNull(fns.get(0).get("web_hook_url"));
  }

  @Test
  @SuppressWarnings("unchecked")
  void testSwaigDefaultsAbsentWhenNoFunctions() {
    // Gated on `if functions:` in the reference — no functions, no defaults block.
    AgentBase agent =
        AgentBase.builder().name("test").route("/a").authUser("u").authPassword("p").build();
    agent.setPromptText("Test");

    var swml = agent.renderSwml("http://localhost:3000");
    var swaig = swaigOf(swml);
    assertNull(swaig.get("defaults"), "no functions → no SWAIG.defaults");
  }

  /** Pull the {@code ai.SWAIG} object out of a rendered SWML document, or an empty map. */
  @SuppressWarnings("unchecked")
  private static java.util.Map<String, Object> swaigOf(java.util.Map<String, Object> swml) {
    var sections = (java.util.Map<String, Object>) swml.get("sections");
    var main = (java.util.List<java.util.Map<String, Object>>) sections.get("main");
    for (var verb : main) {
      if (verb.containsKey("ai")) {
        var ai = (java.util.Map<String, Object>) verb.get("ai");
        var swaig = (java.util.Map<String, Object>) ai.get("SWAIG");
        return swaig == null ? java.util.Map.of() : swaig;
      }
    }
    return java.util.Map.of();
  }

  // ======== Environment variable auth ========

  @Test
  void testEnvVarAuthUser() {
    String envUser = System.getenv("SWML_BASIC_AUTH_USER");
    if (envUser != null && !envUser.isEmpty()) {
      AgentBase agent = AgentBase.builder().name("test").build();
      assertEquals(envUser, agent.getAuthUser());
    }
  }

  @Test
  void testEnvVarAuthPassword() {
    String envPass = System.getenv("SWML_BASIC_AUTH_PASSWORD");
    if (envPass != null && !envPass.isEmpty()) {
      AgentBase agent = AgentBase.builder().name("test").authUser("u").build();
      assertEquals(envPass, agent.getAuthPassword());
    }
  }
}
